Budget App
Josphat205/budget-app pull request #3
Opened 2022-12-20 12:01 UTC by Josphat205

### **IN THIS BRANCH**

- Splash screen

- Added a simple page with the name of your app 

- The user should be able to register in the app with full name, email and password 
- The user can log into the app using email and password.
- If the user is not logged in, they can't access pages that require the user to be logged in

- When the user logs in, they are presented with the categories page.
  - For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
  - When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
  - There is a button "add a new category" at the bottom that brings the user to the page to create a new category.
  - Transactions page For a given category, the list of transactions is presented, ordered by the most recent
  - There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.

- Added a new transaction page
-  AddedTesting of model and controller

2023-03-21 11:17 UTC, MeqdamAlqudah requested changes
Hi @lomantech , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![image](https://user-images.githubusercontent.com/74744787/226582627-4206c22c-e3cc-4ba8-9f83-6359b0cab66f.png)


## Highlights
:+1: categories blocks
:+1: files structure

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-21 11:17 UTC, MeqdamAlqudah commented on README.md
> +I would like to thank microverse and my group members for the support they gave me during project development
- [ ] Please the README should contain an "Acknowledgements" section or similar that gives appropriate credit to [Gregoire Vella on Behance](https://www.behance.net/gregoirevella) the [author of the original design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), as required by the [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/).

2023-03-21 11:17 UTC, MeqdamAlqudah commented on app/views/shared/_splash.html.erb
> +      <div class="d-flex">
- [ ] Please the Splash screen should contain the name of the project , I can see that you add the title but for some reason the title color is white , fix it please and make sure it is visible to the user 
![image](https://user-images.githubusercontent.com/74744787/226576959-2640a98e-64c4-4411-8e6b-8727d7ab32a6.png)

2023-03-21 11:17 UTC, MeqdamAlqudah commented on app/models/expense.rb
> +  belongs_to :group
- [x] Please there should be many to many relation between the Expense and the Group, models as in the database schema as I can see you create a one to many relation
![image](https://user-images.githubusercontent.com/74744787/226580903-4716daaa-fcc1-4cc2-8b9b-872bd84adb54.png)

2023-03-21 11:17 UTC, MeqdamAlqudah commented on app/views/groups/new.html.erb
> +        <%= form.label :icon, 'Icon link', class: "form-label" %>
- [ ] Please make sure that add a category and Add a new transaction design matches the one in the original design
![image](https://user-images.githubusercontent.com/74744787/226582940-1bb253bf-790d-4594-ad58-d07b3b1f9e0b.png)
![image](https://user-images.githubusercontent.com/74744787/226590231-69b4163f-6a4b-4e7d-8715-5a3b67657a06.png)
The design 
![image](https://user-images.githubusercontent.com/74744787/226590295-c7969514-c050-4bd2-8c1a-43631934c6dc.png)

2023-03-23 07:50 UTC, Josphat205 commented on app/models/expense.rb
> +  belongs_to :group
Added

2023-03-23 09:01 UTC, HAMMAS-SALEEM commented on app/views/shared/_splash.html.erb
> +      <div class="d-flex">
👍

2023-03-23 09:26 UTC, HAMMAS-SALEEM reviewed
# Invalid Submission :red_circle:

![invalid-submission](https://user-images.githubusercontent.com/93039359/221218445-05489541-f840-492c-878e-0587cc2b3702.gif)

## Hey @Josphat205 :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following some requirements

Good job on implementing some of the requirements but I cannot proceed review of your pull request because there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

## Mandatory Requirements ♻️

- [ ] It would be great if you configure stylelint in your linters setup because you have some code of CSS to check its errors you should have stylelint configured in your project 🤔

2023-03-23 11:19 UTC, elisha2kyakpo1 approved these changes
Hi 👋 @Josphat205, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

👍 You did well fixing the required changes and adding the linters for the CSS.

## Optional suggestions

- [ ] Let's always remember that there is a difference between GitHub flow and gitflow when we are setting up GitHub workflows. Your project was supposed to be invalidated in the first place.

![git](https://user-images.githubusercontent.com/53124548/227187678-fa88dceb-9f2d-4ff3-8b95-6f4b65176f3e.png)


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 11:45 UTC, merged